@startuml
left to right direction
actor 学生
actor 老师
actor 管理员

学生 --> (选课)
学生 --> (查询课程)
学生 --> (查看分数)
学生 --> (修改个人信息)

(添加课程) <-- 老师
(删除课程) <-- 老师
(修改课程信息) <-- 老师
(添加实验) <-- 老师
(删除实验) <-- 老师
(修改实验信息) <-- 老师
(评分) <-- 老师
(修改个人信息) <-- 老师

管理员 --> (添加用户)
管理员 --> (删除用户)
管理员 --> (修改用户信息)
管理员 --> (修改个人信息)
@enduml