@startuml
class 学生{
学号
密码
姓名
班级
github
}

class 老师{
教师编号
密码
姓名
}

class 管理员{
管理员编号
密码
姓名
}

class 课程表{
课程编号
创建者
课程名
}

class 实验表{
实验编号
学号
课程编号
实验名
总分得分
实验内容
}

class 分数表{
实验编号
学号
总分得分
得分1
得分2
得分3
得分4
得分5
老师点评
}

class 选课表{
课程编号
学号
}

管理员 "*"--"*" 学生 :管理用户
管理员 "*"--"*" 老师 :管理用户

老师 "1"--"*" 课程表 :排课
老师 "1"--"*" 实验表 :安排实验
老师 "1"--"*" 分数表 :打分

学生 "*"--"*" 选课表 :选课
学生 "*"--"*" 实验表 :查看实验
学生 "1"--"*" 分数表 :查看分数
@enduml